// frontend/preact-app/src/components/Navbar.jsx
import { h } from 'preact';

function Navbar({ currentPage, setCurrentPage }) {
    return (
        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
            <div className="container-fluid">
                <a
                    className="navbar-brand"
                    href="#"
                    onClick={() => setCurrentPage('tic-tac-toe')}
                >
                    Preact - Tic-Tac-Toe
                </a>
                <button
                    className="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                >
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarNav">
                    <ul className="navbar-nav ms-auto">
                        <li className="nav-item">
                            <a
                                className={`nav-link ${currentPage === 'tic-tac-toe' ? 'active' : ''}`}
                                href="#"
                                onClick={() => setCurrentPage('tic-tac-toe')}
                            >
                                Tic Tac Toe
                            </a>
                        </li>
                        <li className="nav-item">
                            <a
                                className={`nav-link ${currentPage === 'todo' ? 'active' : ''}`}
                                href="#"
                                onClick={() => setCurrentPage('todo')}
                            >
                                Todo List
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    );
}

export default Navbar;

// frontend/solid-app/src/components/Navbar.tsx
import { Component } from 'solid-js';

interface NavbarProps {
    currentPage: string;
    setCurrentPage: (page: string) => void;
}

const Navbar: Component<NavbarProps> = (props) => {
    return (
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" onClick={(e) => { e.preventDefault(); props.setCurrentPage('tictactoe'); }}>
                    Solid.js - Tic-Tac-Toe
                </a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a
                                class={`nav-link ${props.currentPage === 'tictactoe' ? 'active' : ''}`}
                                href="#"
                                onClick={(e) => { e.preventDefault(); props.setCurrentPage('tictactoe'); }}
                            >
                                Tic Tac Toe
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                class={`nav-link ${props.currentPage === 'todo' ? 'active' : ''}`}
                                href="#"
                                onClick={(e) => { e.preventDefault(); props.setCurrentPage('todo'); }}
                            >
                                Todo List
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    );
};

export default Navbar;
